repos:
# -   repo: local
#     hooks:
#     -   id: mypy
#         name: mypy
#         entry: pipenv run make check
#         language: system
#     -   id: pylint 
#         name: pylint
#         entry: pipenv run pylint --ignore=infra,app.py
#         language: system
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/isort
    rev: 5.7.0
    hooks:
    -   id: isort